### PR TITLE
feat: merge go1.17.4 and add factory for uTLS proxy

### PR DESCRIPTION
**Pull request by bassosimone**
* merge with go1.17.4

* add (experimental) factory for uTLS proxy

### CODE REVIEW

**Comment by bynf** [comment]
Hello @bassosimone,
Thank you for this repository. I think you are working on best library in community.
I tried oohttp + utls with proxy. It's not changing tls fingerprint for proxy connections.
I just started following the library, so I haven't had a chance to dig deeper yet. Just wanted to post here for feedback.

**Comment by bassosimone** [comment]
@bynf Thanks for letting me know! I think there may be something wrong with the proxy factory. I will take a look in the next few days and see what's wrong! ✌️

**Comment by bassosimone** [comment]
@frankwalter1301 you're right, this is the issue. I should have fixed it in https://github.com/ooni/oohttp/pull/19 and I've also added an example usage in https://github.com/ooni/oohttp/pull/20 (which works for me). It would be great if you folks could test it!

**Comment by frankwalter1301** [comment]
It works very well!

**Pull request merged**
